/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bo.edu.uagrm.ficct.inf310sb.ui;

import bo.edu.uagrm.ficct.inf310sb.arboles.ArbolB;
import bo.edu.uagrm.ficct.inf310sb.arboles.IArbolBusqueda;
import bo.edu.uagrm.ficct.inf310sb.arboles.excepciones.ExcepcionOrdenInvalido;

public class ÁrbolB extends javax.swing.JFrame {

    IArbolBusqueda<String, String> arbol;

    /**
     * Creates new form ÁrbolB
     */
    public ÁrbolB() {
        try {
            this.arbol = new ArbolB<>();
        } catch (ExcepcionOrdenInvalido e) {

        }
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        nombre = new javax.swing.JTextField();
        significado = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        recorridos = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        Insertar = new javax.swing.JMenuItem();
        Eliminar = new javax.swing.JMenuItem();
        Buscar = new javax.swing.JMenuItem();
        Cargar = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        InOrden = new javax.swing.JMenuItem();
        PreOrden = new javax.swing.JMenuItem();
        PostOrden = new javax.swing.JMenuItem();
        Nivel = new javax.swing.JMenuItem();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 51));

        jPanel2.setBackground(new java.awt.Color(12, 23, 25));

        jLabel2.setForeground(new java.awt.Color(153, 153, 153));
        jLabel2.setText("Nombre:");

        jLabel3.setForeground(new java.awt.Color(153, 153, 153));
        jLabel3.setText("Significado:");

        jLabel4.setForeground(new java.awt.Color(153, 153, 153));
        jLabel4.setText("Recorrido :");

        nombre.setBackground(new java.awt.Color(153, 153, 153));
        nombre.setForeground(new java.awt.Color(12, 23, 25));

        significado.setBackground(new java.awt.Color(153, 153, 153));
        significado.setForeground(new java.awt.Color(12, 23, 25));
        significado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                significadoActionPerformed(evt);
            }
        });

        recorridos.setBackground(new java.awt.Color(153, 153, 153));
        recorridos.setColumns(20);
        recorridos.setForeground(new java.awt.Color(12, 23, 25));
        recorridos.setRows(5);
        jScrollPane1.setViewportView(recorridos);

        jLabel1.setFont(new java.awt.Font("Roboto Bk", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 153, 153));
        jLabel1.setText("SIGNIFICADOS DE NOMBRES");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                            .addGap(24, 24, 24)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4)
                                .addComponent(jLabel3))
                            .addGap(426, 426, 426))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(109, 109, 109)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(significado, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabel2)
                        .addGap(32, 32, 32)
                        .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(48, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(123, 123, 123))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jLabel1)
                .addGap(34, 34, 34)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(significado, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(64, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addGap(80, 80, 80))))
        );

        jMenu1.setText("Metodos");

        Insertar.setText("Insertar");
        Insertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InsertarActionPerformed(evt);
            }
        });
        jMenu1.add(Insertar);

        Eliminar.setText("Eliminar");
        Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarActionPerformed(evt);
            }
        });
        jMenu1.add(Eliminar);

        Buscar.setText("Buscar");
        Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarActionPerformed(evt);
            }
        });
        jMenu1.add(Buscar);

        Cargar.setText("Cargar");
        Cargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CargarActionPerformed(evt);
            }
        });
        jMenu1.add(Cargar);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Recorridos");

        InOrden.setText("Recorrido InOrden");
        InOrden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InOrdenActionPerformed(evt);
            }
        });
        jMenu2.add(InOrden);

        PreOrden.setText("Recorrido PreOrden");
        PreOrden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PreOrdenActionPerformed(evt);
            }
        });
        jMenu2.add(PreOrden);

        PostOrden.setText("Recorrido PostOrden");
        PostOrden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PostOrdenActionPerformed(evt);
            }
        });
        jMenu2.add(PostOrden);

        Nivel.setText("Recorrido Por Niveles");
        Nivel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NivelActionPerformed(evt);
            }
        });
        jMenu2.add(Nivel);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void InsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InsertarActionPerformed
        // TODO add your handling code here:
        arbol.insertar(nombre.getText(), significado.getText());
    }//GEN-LAST:event_InsertarActionPerformed

    private void significadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_significadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_significadoActionPerformed

    private void BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarActionPerformed
        // TODO add your handling code here:
        significado.setText(arbol.buscar(nombre.getText()));
    }//GEN-LAST:event_BuscarActionPerformed

    private void CargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CargarActionPerformed
        // TODO add your handling code here:
        arbol.insertar("Gabriel", "El que tiene la fuerza de Dios");
        arbol.insertar("Eloy", "El elegido");
        arbol.insertar("Esteban", "Victorioso");
        arbol.insertar("Alina", "Amiga noble");
        arbol.insertar("Roberto", "De fama brillante");
        arbol.insertar("Juan", "Pleno de gracia");
        arbol.insertar("Sheila", "Celestial");
        arbol.insertar("Leonardo", "Fuerte como león ");
        arbol.insertar("María", "Señora");
        arbol.insertar("Enzo", "Amo de la casa");
        arbol.insertar("Moisés", "Salvado de las aguas");
        arbol.insertar("Lucía", "Luminosa");
        arbol.insertar("Mateo", "Don del señor");
        arbol.insertar("Emma", "La que es fuerte");
        arbol.insertar("Fabricio", "Hijo de artesano");
        arbol.insertar("Inés", "La pura");
        arbol.insertar("Jairo", "El que es iluminado");
        arbol.insertar("Daniel", "Justicia de Dios");
        arbol.insertar("Carlos", "Hombre libre");
        arbol.insertar("Sebastián", "Venerable");
        arbol.insertar("Martín", "Guerrero");
        arbol.insertar("Angélica", "Enviada de Dios");
        arbol.insertar("Rocio", "Lágrimas de flor");
        arbol.insertar("Edmundo", "Paz bendita");
        arbol.insertar("Alejandro", "Protector de los hombres");
        arbol.insertar("Eva", "La que da vida");
        arbol.insertar("Emanuel", "Dios con nosotros");
        ((ArbolB)arbol).mostrar();
    }//GEN-LAST:event_CargarActionPerformed

    private void PostOrdenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PostOrdenActionPerformed
        // TODO add your handling code here:
        recorridos.setText("" + arbol.recorridoEnPostOrden() + "");
    }//GEN-LAST:event_PostOrdenActionPerformed

    private void InOrdenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InOrdenActionPerformed
        // TODO add your handling code here:
        recorridos.setText("" + arbol.recorridoEnInOrden() + "");
    }//GEN-LAST:event_InOrdenActionPerformed

    private void PreOrdenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PreOrdenActionPerformed
        // TODO add your handling code here:
        recorridos.setText("" + arbol.recorridoEnPreOrden() + "");
    }//GEN-LAST:event_PreOrdenActionPerformed

    private void NivelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NivelActionPerformed
        // TODO add your handling code here:
        recorridos.setText("" + arbol.recorridoPorNiveles() + "");
    }//GEN-LAST:event_NivelActionPerformed

    private void EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarActionPerformed
        // TODO add your handling code here:
        String valor = arbol.eliminar(nombre.getText());
    }//GEN-LAST:event_EliminarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ÁrbolB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ÁrbolB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ÁrbolB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ÁrbolB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ÁrbolB().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Buscar;
    private javax.swing.JMenuItem Cargar;
    private javax.swing.JMenuItem Eliminar;
    private javax.swing.JMenuItem InOrden;
    private javax.swing.JMenuItem Insertar;
    private javax.swing.JMenuItem Nivel;
    private javax.swing.JMenuItem PostOrden;
    private javax.swing.JMenuItem PreOrden;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nombre;
    private javax.swing.JTextArea recorridos;
    private javax.swing.JTextField significado;
    // End of variables declaration//GEN-END:variables
}
